name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
    
    - name: Cache pipx and poetry dependencies
      uses: actions/cache@v2
      with:
        path: |
          ~/.local/pipx
          ~/.cache/pypoetry
        key: ${{ runner.os }}-python-${{ hashFiles('**/poetry.lock') }}-pipx-poetry
        restore-keys: |
          ${{ runner.os }}-python-${{ hashFiles('**/poetry.lock') }}-pipx-poetry
          ${{ runner.os }}-python- 

    - name: Install pipx and poetry
      run: |
        python3 -m pip install --user pipx
        python3 -m pipx ensurepath
        pipx install poetry

    - name: Install dependencies
      run: poetry install

    - name: Lint with black
      run: poetry run black --check . 

    - name: Test with pytest
      run: poetry run pytest
